// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBvTylclh3Mkl_udVdVuYWcl10afan3Tk',
    appId: '1:525999248096:web:7ffe8aab8fdf400267f685',
    messagingSenderId: '525999248096',
    projectId: 'tugas9mobile-4f643',
    authDomain: 'tugas9mobile-4f643.firebaseapp.com',
    storageBucket: 'tugas9mobile-4f643.firebasestorage.app',
    measurementId: 'G-6RY1GGB2D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTAlKXqyuCbp9duv8fKMov4LxK1bMJlFo',
    appId: '1:525999248096:android:2087a76b1be858f867f685',
    messagingSenderId: '525999248096',
    projectId: 'tugas9mobile-4f643',
    storageBucket: 'tugas9mobile-4f643.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS_lASo3__OiLGLDlMWPzk0bN2Y2vZ-VU',
    appId: '1:525999248096:ios:4c25ac1715c3296b67f685',
    messagingSenderId: '525999248096',
    projectId: 'tugas9mobile-4f643',
    storageBucket: 'tugas9mobile-4f643.firebasestorage.app',
    iosBundleId: 'com.example.aplikasihsnews',
  );
}
